### ISSUE TITLE
Tower Services

### ISSUE THREAD

**Issue by plebhash** [demand-open-source/demand-sv2-connection#1]
It seems this is project is walking in the direction of revolving around `tokio`, which I'm fully supportive of.

I'm writing this issue to propose the exploration of [`tower`](https://crates.io/crates/tower) on this crate.
Supported by the Tokio community, Tower is described as:
> a library of modular and reusable components for building robust networking clients and servers.

Providing [`Service`](https://docs.rs/tower/latest/tower/trait.Service.html) trait implementation for SRI roles (and utils e.g.: `network_helpers_sv2`) seems like an interesting direction to standardize roles APIs.

I'm curious to hear your thoughts @Fi3

**Comment by plebhash** [comment]
Some highlights of `tower`:

> Tower aims to make it as easy as possible to build robust networking clients and servers. It is protocol agnostic, but is designed around a request / response pattern. If your protocol is entirely stream based, Tower may not be a good fit.
>
> Tower provides a simple core abstraction, the [Service](https://docs.rs/tower/latest/tower/trait.Service.html) trait, which represents an asynchronous function taking a request and returning either a response or an error. This abstraction can be used to model both clients and servers.

> Generic components, like [timeouts](https://docs.rs/tower/latest/tower/timeout/), [rate limiting](https://docs.rs/tower/latest/tower/limit/rate), and [load balancing](https://docs.rs/tower/latest/tower/balance/), can be modeled as [Service](https://docs.rs/tower/latest/tower/trait.Service.html)s that wrap some inner service and apply additional behavior before or after the inner service is called. This allows implementing these components in a protocol-agnostic, composable way. Typically, such services are referred to as middleware.
>
> An additional abstraction, the [Layer](https://docs.rs/tower/latest/tower/trait.Layer.html) trait, is used to compose middleware with [Service](https://docs.rs/tower/latest/tower/trait.Service.html)s. If a [Service](https://docs.rs/tower/latest/tower/trait.Service.html) can be thought of as an asynchronous function from a request type to a response type, a [Layer](https://docs.rs/tower/latest/tower/trait.Layer.html) is a function taking a [Service](https://docs.rs/tower/latest/tower/trait.Service.html) of one type and returning a [Service](https://docs.rs/tower/latest/tower/trait.Service.html) of a different type. The [ServiceBuilder](https://docs.rs/tower/latest/tower/struct.ServiceBuilder.html) type is used to add middleware to a service by composing it with multiple multiple [Layer](https://docs.rs/tower/latest/tower/trait.Layer.html)s.

# Library Support

> A number of third-party libraries support Tower and the [Service](https://docs.rs/tower/latest/tower/trait.Service.html) trait. The following is an incomplete list of such libraries:
> 
> - [hyper](https://crates.io/crates/hyper): A fast and correct low-level HTTP implementation.
> - [tonic](https://crates.io/crates/tonic): A [gRPC-over-HTTP/2](https://grpc.io/) implementation built on top of [hyper](https://crates.io/crates/hyper). See [here](https://github.com/hyperium/tonic/tree/master/examples/src/tower) for examples of using [tonic](https://crates.io/crates/tonic) with Tower.
> - [warp](https://crates.io/crates/warp): A lightweight, composable web framework. See [here](https://docs.rs/warp/0.2.5/warp/fn.service.html) for details on using [warp](https://crates.io/crates/warp) with Tower.
> - [tower-lsp](https://crates.io/crates/tower-lsp) and its fork, [lspower](https://crates.io/crates/lspower): implementations of the [Language Server Protocol](https://microsoft.github.io/language-server-protocol/) based on Tower.
> - [kube](https://crates.io/crates/kube): Kubernetes client and futures controller runtime. [kube::Client](https://docs.rs/kube/latest/kube/struct.Client.html) makes use of the Tower ecosystem: [tower](https://crates.io/crates/tower), [tower-http](https://crates.io/crates/tower-http), and [tower-test](https://crates.io/crates/tower-test). See [here](https://github.com/clux/kube-rs/blob/master/examples/custom_client.rs) and [here](https://github.com/clux/kube-rs/blob/master/examples/custom_client_trace.rs) for examples of using [kube](https://crates.io/crates/kube) with Tower.

**Comment by Fi3** [comment]
I prefer leave it as simple as possible and not adding any other dependency. Where I use it, I implement the generic component that tower offer on top of it. I don't use tower cause I don't want deps, but you can  create a lib that import this and tower and imple a Service using this library. Closing for now, but ty for the suggestion.
